export const CharacterActionTypes = {
	FETCH_CHARACTERS_START: 'FETCH_CHARACTERS_START',
	FETCH_CHARACTERS_SUCCESS: 'FETCH_CHARACTERS_SUCCESS',
	FETCH_CHARACTERS_FAILURE: 'FETCH_CHARACTERS_FAILURE',
	SINGLE_CHARACTER: 'SINGLE_CHARACTER',

	SEARCH: 'SEARCH',
	SEARCH_QUERY: 'SEARCH_QUERY',
}